version: '3.8'

services:
  # Option 1: Local Storage with Volume
  blog-local:
    build: .
    ports:
      - "9090:9090"
    environment:
      - FILE_STORAGE_TYPE=local
      - FILE_STORAGE_LOCAL_PATH=/app/uploads/
      - FILE_STORAGE_BASE_URL=http://localhost:9090/api/files/uploads/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/blogdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=pass
    volumes:
      - ./uploads:/app/uploads  # Persistent volume for local files
    depends_on:
      - db

  # Option 2: AWS S3 Storage
  blog-s3:
    build: .
    ports:
      - "9091:9090"
    environment:
      - FILE_STORAGE_TYPE=s3
      - FILE_STORAGE_S3_BUCKET=your-blog-bucket
      - FILE_STORAGE_S3_REGION=us-east-1
      - FILE_STORAGE_BASE_URL=https://your-blog-bucket.s3.amazonaws.com/uploads/
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/blogdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=pass
    depends_on:
      - db

  # Database
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=blogdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
